### ISSUE TITLE
Dokumentation schreiben

### ISSUE THREAD

**Issue by enze-l** [EMM-Gruppe8/Morphy#22]

**Comment by vantezzen** [comment]
Definition der Anforderungen und deren Erfüllungsgrad
Erläuterung der verwendeten Technologien
Erläuterung des Systems samt Abbildungen
Integration eines Systembildes
Gesamteinschätzung des Projekts und kurze Selbsteinschätzung je Gruppenmitglied (Arbeitsanteile, Erkenntnisgewinne, überwundene Hürden etc.)
Literaturverzeichnis
Umfang min. 5 max. 10 Seiten
Inhalte siehe Vorlesungsunterlagen (insbesondere 01-EMM_Einleitung.pdf)
