### ISSUE TITLE
Menues don't turn with device

### ISSUE THREAD

**Issue by enze-l** [EMM-Gruppe8/Morphy#36]
If a game is paused and the player walkes on the ceiling, the menu still is in the original position.

**Comment by vantezzen** [comment]
Problem is that the Menu relies on "Update" which won't get called when the game is paused. Is there an alternative way to achieve this?

**Comment by enze-l** [comment]
> Problem is that the Menu relies on "Update" which won't get called when the game is paused. Is there an alternative way to achieve this?

I don't think it is important that the menu rotates interactivaly while the game is paused. It could even lead to unwanted sideeffects if the player stops the game, rotates the phone and continues playing.

Having said that I think it is enough if you would set the rotation of the menu once in "UpdatePauseStatus()" in the beginning.  A simple way to figure out the rotation is read out "Input.acceleration.y". If it is negative, the device is turned one direction, if is positiv the other one.
