### ISSUE TITLE
Leveldesign ausdenken

### ISSUE THREAD

**Issue by enze-l** [EMM-Gruppe8/Morphy#8]

**Comment by cmsk1** [comment]
Wollen wir zur Präsentation noch ein drittes Level haben? in unseren Anforderungen haben wir ja drei Level erwähnt. 
Ich kann anbieten, morgen (Montag 05.07) dabei zu helfen.

**Comment by enze-l** [comment]
Ja, wir brauchen auf jeden Fall noch ein Level. Auch Level 2 funktioniert leider wegen der Spielmechanik nicht mehr wir geplant. Wir können uns gerne zusammen hinsetzen.
